feat: new scratch image of grafana

diff --git a/salami/grafana/thin-image/Dockerfile b/salami/grafana/thin-image/Dockerfile
--- a/salami/grafana/thin-image/Dockerfile
+++ b/salami/grafana/thin-image/Dockerfile
@@ -2,24 +2,42 @@ FROM alpine:3.20 AS builder
 
 ENV GRAFANA_VERSION=12.1.1
 WORKDIR /tmp
-RUN apk add --no-cache curl tar git && \
+RUN apk add --no-cache curl tar git ca-certificates shadow util-linux su-exec && \
     curl -fsSL -o grafana.tar.gz "https://dl.grafana.com/oss/release/grafana-${GRAFANA_VERSION}.linux-amd64.tar.gz" && \
     mkdir /grafana && \
-    mkdir rootfs && \
     tar -xzf grafana.tar.gz -C /grafana --strip-components=1 && \
-    git clone https://github.com/OpenSalami/rootfs.git /rootfs
+    git clone https://github.com/OpenSalami/rootfs.git /prebuildfs
 
+# Ensure all .sh scripts are executable (does not fail if none found)
+RUN find /prebuildfs/prebuildfs/opt/salami/scripts -type f -name '*.sh' -exec chmod +x {} \; || true
+COPY rootfs /rootfs
+RUN find /rootfs/opt/salami/scripts -type f -name '*.sh' -exec chmod +x {} \; || true
+RUN touch /grafana/conf/sample.ini
+RUN mkdir -p /opt/salami/scripts && cp -r /rootfs/opt/salami/scripts/* /opt/salami/scripts/ && cp /prebuildfs/prebuildfs/opt/salami/scripts/* /opt/salami/scripts/
+
+ENV GRAFANA_BASE_DIR=/grafana 
+
+RUN /opt/salami/scripts/grafana/postunpack.sh
 
 FROM scratch
 
 COPY --from=builder /grafana /grafana
 COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
 COPY --from=builder /bin/sh /bin/sh
-COPY --from=builder /rootfs/opt/scripts /opt/scripts
+COPY --from=builder /lib/ld-musl-aarch64.so.1 /lib/
+COPY --from=builder /prebuildfs/prebuildfs/opt/salami/scripts/ /opt/salami/scripts/
+
+COPY --from=builder /rootfs/opt/ /opt
+COPY --from=builder /bin/busybox /bin/busybox
+RUN ["/bin/busybox", "--install", "-s", "/bin"]
+COPY --from=builder /sbin/su-exec /sbin/su-exec
+
+
+ENV APP_VERSION="${GRAFANA_VERSION}}" \
+    SALAMI_APP_NAME="grafana" \
+    PATH="/opt/salami/mysql/bin:/opt/salami/common/bin:/opt/salami/grafana/bin:$PATH"
 
 EXPOSE 3000
 
-WORKDIR /grafana
-
-ENTRYPOINT ["/grafana/bin/grafana-server"]
-CMD ["--homepath=/grafana", "--config=/grafana/conf/defaults.ini"]
+ENTRYPOINT [ "/bin/sh", "/opt/salami/scripts/grafana/entrypoint.sh" ]
+CMD [ "/bin/sh", "/opt/salami/scripts/grafana/run.sh" ]
